// Copyright 2024 bhipp
// initial tests to compare output generated by testMonetaryAmountCreateOutput
// to expected output
#include<iostream>
using std::cout;
using std::endl;
#include<fstream>
using std::ifstream;
#include<cstring>

int main() {
  ifstream student_file("studentoutput.txt");
  if ( !student_file.good() )
    cout << "Issue with student output. Check studentoutput.txt"
         << endl;
  ifstream correct_file("expectedoutput.txt");
  if ( !correct_file.good() )
    cout << "Issue with expected output. Confirm that the file "
         << "\"expectedoutput.txt\" is saved in the current directory "
         << "and then rerun the test." << endl;
  int line = 1;
  char student_line[101] = "";
  char correct_line[101] = "";
  student_file.getline(student_line, 100);
  correct_file.getline(correct_line, 100);
  while ( correct_file.good() ) {
    if ( student_file.good() ) {
      if ( strcmp(correct_line, student_line) == 0 )
        cout << "Matched line " << line << endl;
      else
        cout << "Mismatch on line " << line << "\n\tExpected output: \""
             << correct_line << "\"\n\tStudent output: \"" << student_line
             << "\"" << endl;
      student_file.getline(student_line, 100);
    } else {
      cout << "Mismatch on line " << line << "\n\tExpected output: \""
           << correct_line << "\"\n\tStudent output: \"\"" << endl;
    }
    ++line;
    correct_file.getline(correct_line, 100);
  }
  return 0;
}

